Add COBS_STREAM config option
This commit adds CONFIG_COBS_STREAM option to enable COBS for streams
instead of keeping it a default.

When it was by default enabled it was generating these errors for code
that used COBS without streams:

/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c: In function 'cobs_encode_stream_single':
/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c:156:11: error: unused variable 'num_pulled' [-Werror=unused-variable]
  156 |    size_t num_pulled = net_buf_pull_across_fragments(&encode->buf, &zero, 1);
      |           ^~~~~~~~~~
/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c:232:10: error: unused variable 'num_pulled' [-Werror=unused-variable]
  232 |   size_t num_pulled = net_buf_pull_across_fragments(&encode->buf, output, 1);
      |          ^~~~~~~~~~
/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c:264:10: error: unused variable 'num_pulled' [-Werror=unused-variable]
  264 |   size_t num_pulled = net_buf_pull_across_fragments(&encode->buf, output, 1);
      |          ^~~~~~~~~~

Signed-off-by: Sebastian Panceac <sebastian.panceac@ext.grandcentrix.net>